### ISSUE TITLE
CIL harvesting and metadata transformation processes 

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/damsmanager#289]
### Descriptive summary
Write scripts for regular harvesting and transformation of content (files and metadata) from the Cell Image Library GitHub repository: https://github.com/slash-segmentation/CIL_Public_Data_JSON

### Documentation
1. Outline of Ongoing Harvesting processes https://docs.google.com/document/d/1Eg2024XATxuwdzFtoLTNujalK2SDR_s6-Sg6zyUC9wE/edit#heading=h.caf5ayev1pza
2. Mapping for creation of subject heading ingest file and object level record ingest file: https://docs.google.com/spreadsheets/d/1NnYw3bgNraJ9hZCH1SOKijh_JvJh3So1LpDC24vu7h8/edit#gid=1321122337

### Related work
* https://github.com/ucsdlib/damspas/issues/449
* https://github.com/ucsdlib/damspas/issues/436

**Comment by lsitu** [comment]
@arwenhutt Can you give me the permission to the share doc [Mapping for creation of subject heading ingest file and object level record ingest file](https://docs.google.com/spreadsheets/d/1NnYw3bgNraJ9hZCH1SOKijh_JvJh3So1LpDC24vu7h8/edit#gid=1321122337) so that I can take a look? Thanks.

**Comment by arwenhutt** [comment]
@lsitu done!

**Comment by lsitu** [comment]
@arwenhutt Could you show me an example for row#75 `Create a new row for child component for json file` in [Mapping for creation of subject heading ingest file and object level record ingest file](https://docs.google.com/spreadsheets/d/1NnYw3bgNraJ9hZCH1SOKijh_JvJh3So1LpDC24vu7h8/edit#gid=1321122337)? Thanks.

**Comment by arwenhutt** [comment]
@lsitu In other words, we want to add a final child component to the object with the source metadata (the json file itself) attached as a file.  We aren't mapping all of the source metadata into the dams so this gives a user access to the full source metadata in case they need it. 

Let me know if you would still like an example ingest file, I can do that but this week is very busy and I'm not sure when I'll be able to get to it!

**Comment by lsitu** [comment]
@arwenhutt Are there any identifiers in the CIL object that can be used to check whether a JSON file (object) is ingested or not?
For date:creation mapping (row#7-9) in [Mapping for creation of subject heading ingest file and object level record ingest file],(https://docs.google.com/spreadsheets/d/1NnYw3bgNraJ9hZCH1SOKijh_JvJh3So1LpDC24vu7h8/edit#gid=1321122337), is three `CIL_CCDB.CIL.CORE.ATTRIBUTION.DATE` values in an array or just one? Could you show me an example? Thanks.

**Comment by mcritchlow** [comment]
Hi @lsitu - I can help with the 2nd part, I'm not clear on the 1st part of the question re: identifiers in the object.

For the dates, I believe it can be an array with 1-m values. 

I did a quick grep in the github repo `grep -iRl "DATE" ./` to find some examples.

Here's one: Version8_6/DATA/CIL_PUBLIC_DATA/40685.json

I'm not sure that answers your question or not.

**Comment by lsitu** [comment]
@arwenhutt Yes, I was thinking about the step above. In this case, we may need an identifier with the file name. At this time, since we'll download the new JSON source files from github https://github.com/slash-segmentation/CIL_Public_Data_JSON and place them in a folder with a date like `cil_harvest_[YYYY-MM-DD]`, I think it should work to just do a nightly process to convert all those JSON source files at one time. But while moving forward, I am not sure whether there will be any exceptions or not.
Also, the mapping for `Note:description` in line#43 (`CIL_CCDB.CIL.CORE.IMAGEDESCRIPTION`) should be `CIL_CCDB.CIL.CORE.IMAGEDESCRIPTION.free_text` (see https://github.com/slash-segmentation/CIL_Public_Data_JSON/blob/master/Version8_6/DATA/CIL_PUBLIC_DATA/10001.json#L125). Is it correct?

**Comment by lsitu** [comment]
@arwenhutt I think the work to support CIL Harvesting is done in the following related tickets:
#291 
#292 
#297 

Do you think how often we should run a cron job to check for new JSON source files added on git hub repository https://github.com/slash-segmentation/CIL_Public_Data_JSON?
Could you give more specifically regarding item `6. Notification of harvest completion sent to [DOMM, JIRA, and Ho Jung]` in https://docs.google.com/document/d/1Eg2024XATxuwdzFtoLTNujalK2SDR_s6-Sg6zyUC9wE/edit#heading=h.caf5ayev1pza? I think we can sent out emails once the work for CIL Harvesting is done.

**Comment by gamontoya** [comment]
@lsitu Is this ticket open because you are waiting on @arwenhutt?

**Comment by hjsyoo** [comment]
@gamontoya Can you update me on the status of this work? Is there anything for me or @arwenhutt to review, or are there some dependencies that need to be addressed first?

**Comment by gamontoya** [comment]
@hjsyoo I think @lsitu can confirm, but I think this work is complete.

**Comment by lsitu** [comment]
@gamontoya / @hjsyoo Yes, the work is done. We just need to setup a cron job to run it: [Create cron job for CIL syn](https://github.com/ucsdlib/cil-sync/issues/2). @rstanonik / @mcritchlow Are we going to setup Kubernetes CronJob for it? Thanks.

**Comment by rstanonik** [comment]
If this should run in kubernetes (or even docker), then are you going to create a docker image? 

I looked at the "Create cron job" link.  The example of running the code looks like

/pub/data2/damsmanager/dams-staging/rdcp-staging/rdcp-0126-cil

If this runs as a cron job, does it always use the same argument "rdcp-0126-cil"?

**Comment by lsitu** [comment]
@rstanonik From the documentation in [1. Outline of Ongoing Harvesting processes](https://docs.google.com/document/d/1Eg2024XATxuwdzFtoLTNujalK2SDR_s6-Sg6zyUC9wE/edit#heading=h.caf5ayev1pza) in the description text, I think we always pass the same path `/pub/data2/damsmanager/dams-staging/rdcp-staging/rdcp-0126-cil` to rdcp-staging to store the results.
Yes, I think we can create a docker file when needed. Do you have an example of the docker image that works for kubernetes? Thanks.

**Comment by rstanonik** [comment]
Take a look at how Vivian set up ldapsync

https://gitlab.com/ucsd-gitlab/library/ldap_sync

**Comment by rstanonik** [comment]
She creates a docker image and pushes it to gitlab's repository.  Then docker or kubernetes can pull it.

**Comment by rstanonik** [comment]
But maybe it should actually go under

https://gitlab.com/surfliner

so it doesn't violate the gitlab academic license.

**Comment by rstanonik** [comment]
I'm trying to run this by hand and it fails because "No such file or directory @ rb_sysopen cil_harvest_2019-02-21/metadata_processed/json_files.txt". 

What input files does it expect to exist?

What output files will it create.

Should this be deployed first to dev or staging?

**Comment by rstanonik** [comment]
What ruby version?

**Comment by arwenhutt** [comment]
@rstanonik I'm not sure but the outline of the harvesting process might have some of the information you need: https://docs.google.com/document/d/1Eg2024XATxuwdzFtoLTNujalK2SDR_s6-Sg6zyUC9wE/edit#heading=h.caf5ayev1pza

**Comment by rstanonik** [comment]
I'm trying to test by hand, so my question is does it expect input files in the path /pub/data2/damsmanager/dams-staging/rdcp-staging/rdcp-0126-cil or does it just produce output files there.  I'd like to test on an empty directory first, but maybe I need to provide some input files there too?

Can you include a Gemfile, so that I can "bundle install" to ensure I get all of the needed gems.

Thanks

**Comment by rstanonik** [comment]
Once I have it running by hand, then I'll try to create a Dockerfile to create an image, but it can run just as a script in the interim.

**Comment by lsitu** [comment]
@rstanonik Thank you very much. I think the Ruby version doesn't matter but it's 2.4.1 in my MAC that ran the tests. The script just run the `Ruby` command to download the source files for CIL Harvesting and here are the list of gems that are used:
require 'open-uri'
require 'json'
require 'byebug'
require 'csv'
require 'fileutils' 

For directory `/pub/data2/damsmanager/dams-staging/rdcp-staging/rdcp-0126-cil`, it need to be created under `rdcp-staging`, which is used to stored the output files there.

**Comment by rstanonik** [comment]
How did you test?

**Comment by rstanonik** [comment]
I get this when I "bundle install"
Could not find gem 'open-uri' in any of the gem sources listed in your Gemfile.

**Comment by rstanonik** [comment]
Apparently, open-uri is part of ruby, so isn't installed as a gem.
https://stackoverflow.com/questions/20544662/unable-to-bundle-install-open-uri/20544806#20544806

**Comment by rstanonik** [comment]
When I run it, it creates the directory for today
cil_harvest_2019-02-21/
cil_harvest_2019-02-21/metadata_processed
cil_harvest_2019-02-21/content_files
cil_harvest_2019-02-21/metadata_source

But fails with
...
../CIL_Public_Data_JSON/Version8_6/DATA/CIL_PUBLIC_DATA/41066.json
../CIL_Public_Data_JSON/Version8_6/DATA/CIL_PUBLIC_DATA/2775.json
../CIL_Public_Data_JSON/Version8_6/DATA/CIL_PUBLIC_DATA/35677.json
./git_changes.sh: line 62: ./cil_harvest_2019-02-21/metadata_processed/json_files.txt: No such file or directory
/home/rstanonik/cil/cil-sync/cil_download.rb:15:in `readlines': No such file or directory @ rb_sysopen - ./cil_harvest_2019-02-21/metadata_processed/json_files.txt (Errno::ENOENT)
        from /home/rstanonik/cil/cil-sync/cil_download.rb:15:in `<main>'

As if it expects cil_harvest_2019-02-21/metadata_processed/json_files.txt to exist

**Comment by lsitu** [comment]
@rstanonik Yep, Ruby could include some of them. I just follow the steps in README ( https://github.com/ucsdlib/cil-sync). Here is the command I use to run it locally:
```./git_changes.sh /Users/lsitu/Documents/git/CIL_Public_Data_JSON /Users/lsitu/Documents/git/cil-sync/rdcp-0126-cil```
`/Users/lsitu/Documents/git/CIL_Public_Data_JSON`: full path to CIL_Public_Data_JSON repository cloned from `git clone git@github.com:slash-segmentation/CIL_Public_Data_JSON.git`
`/Users/lsitu/Documents/git/cil-sync/rdcp-0126-cil`: full path to the folder that stores the output files, which should be the full path to `rdcp-staging/rdcp-0126-cil` as required by the CIL Harvesting process.

**Comment by lsitu** [comment]
For the `No such file or directory` error you got, could you check whether the path to local `CIL_Public_Data_JSON` repository is correct and accessible?

**Comment by rstanonik** [comment]
The path seems correct and accessible.

Here's how I'm testing on my machine

[rstanonik@sandcrab cil]$ ls
CIL_Public_Data_JSON  cil-sync

[rstanonik@sandcrab cil]$ cd cil-sync/
[rstanonik@sandcrab cil-sync]$ ls
cil_csv.rb       cil_harvest_2019-02-21  Gemfile.lock    LICENSE  README.md
cil_download.rb  Gemfile                 git_changes.sh  log.txt

[rstanonik@sandcrab cil-sync]$ ./git_changes.sh ../CIL_Public_Data_JSON .

**Comment by rstanonik** [comment]
It creates
cil_harvest_2019-02-21

**Comment by rstanonik** [comment]
Which consists of empty subdirectories

[rstanonik@sandcrab cil-sync]$ find cil_harvest_2019-02-21/ -print
cil_harvest_2019-02-21/
cil_harvest_2019-02-21/metadata_processed
cil_harvest_2019-02-21/content_files
cil_harvest_2019-02-21/metadata_source

**Comment by rstanonik** [comment]
When I run it with fully qualified paths, rather than relative paths, it now seems to be generating files

For example

./git_changes.sh /home/rstanonik/cil/CIL_Public_Data_JSON /home/rstanonik/cil

**Comment by rstanonik** [comment]
It's still running and has used 191GB so far.
How big do you expect the result to be?
How often should this run?  Nightly?
Will it download the same files each time or does it only download new files?
Each time run it seems to create a directory cil_harvest_YYYY-MM-DD, where YYYY-MM-DD is today's date.

**Comment by lsitu** [comment]
@rstanonik I have no ideas regarding the the initial size of this big batch. Maybe @arwenhutt know more about it?

It's expected to run once a month. And I think run it any time after 3 o'clock in the morning will be fine since damsmanager will run nightly at 3 o'clock to pickup those new files added (https://github.com/ucsdlib/damsmanager/blob/master/src/edu/ucsd/library/xdre/utils/DAMSRoutineManager.java#L45). But just let us know if you want to adjust the schedule.

Yes, it'll only download those new files each time. And it will create a new directory like cil_harvest_YYYY-MM-DD to hold the files downloaded, where YYYY-MM-DD is today's date.

**Comment by hjsyoo** [comment]
@rstanonik I believe it's around 40TB. I'll double check with the db manager and let you know if this estimate is vastly off.

**Comment by rstanonik** [comment]
I've been running a test download to my local drive, but I'm going to stop that and start a download to rdcp-staging.  After it has run a while, I'll have an estimate how long it will take.  Judging from the speed to my local disk, I'd guess 40TB will take about 20 days.  The download will not run on the DAMS machines, but on a machine with a faster connection to the isilon, although I suspect the download from the remote host will be the limiting factor.  From where is the data coming?

**Comment by rstanonik** [comment]
Do you want this to download 24/7?  Or to start and stop?

**Comment by hjsyoo** [comment]
@rstanonik Wow, okay. I believe this is a typical example location for the data: https://cildata.crbs.ucsd.edu/media/videos/10725/10725.jpg

**Comment by rstanonik** [comment]
Oh, so from on-campus.

**Comment by lsitu** [comment]
It's downloaded from `https://cildata.crbs.ucsd.edu/`. For example https://cildata.crbs.ucsd.edu/media/videos/10725/10725.jpg.

**Comment by rstanonik** [comment]
My rough estimate is that data moves about 8TB/day over a 1Gigabit/second connection, at best.   If software is doing some processing of the data, that will slow it down.  Data over an https connection will be slower.  We'll see once it has run for a while.

**Comment by rstanonik** [comment]
@lsitu If something interrupts the download (network problem, machine reboot, etc) and I restart the download, it will figure out where it was and resume from there, rather than start from the beginning, right?

**Comment by lsitu** [comment]
Hmm, with such a long time downloading that could fail at any time, I believe we may need some work to restart the download process, which will skip those files that were downloaded already with checksum/size verification, and also make sure the files are downloaded to the same folder/container. But this this will slow it down a lot.

**Comment by mcritchlow** [comment]
Just a thought, i'm not sure it's practical. But I'll put it out there.

Given that the data is coming from an on-campus source, would it be possible to transfer the data in a more direct manner this first time around? Future updates I imagine will be much smaller, and doing so over the web probably makes sense. But if we could somehow get an Isilon mount they could copy the files into (for example), that might save quite a bit of early processing time.. Thoughts?

**Comment by hjsyoo** [comment]
It never hurts to ask. So I'll ask.

**Comment by rstanonik** [comment]
Data is being written to the Isilon at about 1/2 Gigabit/sec, so 40TB should take about 10 days, if allowed to run 24/7.

**Comment by rstanonik** [comment]
When I move data I try to use rsync, because it can restart a transfer.  But rsync requires a "direct" connection to the filesystem containing the data.  https isn't a direct connection.

**Comment by hjsyoo** [comment]
If the data are also in an accessible filesystem, then you can operate the transfer yourself, @rstanonik ? That might be a more appealing solution all around.

**Comment by rstanonik** [comment]
Yes, if we can NFS (or SMB) mount the data read-only, then I can rsync it.

**Comment by lsitu** [comment]
@mcritchlow It will be nice if that can be worked out, which is much more efficient! Thanks.

**Comment by rstanonik** [comment]
2.6T after 16 hours is about 4T/day, so 40T should take about 10 days.

**Comment by rstanonik** [comment]
Since the application currently doesn't resume where it was, if it is restarted, how does the application only download new content in the future?  The goal is to run it periodically to get new content, right?

**Comment by lsitu** [comment]
@rstanonik When start it again or resume, it'll check for new json files added in the CIL_Public_Data_JSON git repository. If  there are new json files added, the script will download those new json source files. If no new json source files added to the repository, it will exit immediately.

**Comment by hjsyoo** [comment]
@rstanonik I usually hear back from Willy quickly, but I'm still waiting on his response about data transfer. When he does, I'll add you to the email thread.

**Comment by rstanonik** [comment]
After this initial download, what are the steps to run periodically?

git clone or git pull CIL_Public_Data_JSON.git
git clone or git pull cil-sync.git
./git-changes.sh

I assume this will download into a new directory cil_harvest_YYYY-MM-DD

But how will it know which json are new and only download the new json?
Does it look back through previous directories cil_harvest_YYYY-MM-DD?

Thanks.

**Comment by lsitu** [comment]
@rstanonik The script will check for the latest commit in the source data CIL_Public_Data_JSON.git repository and grab the new json files added. So you don't need to run `git clone or git pull CIL_Public_Data_JSON.git` again after this intitiation.

For the CronJob, I think we just need to run the following two commands like:
```git pull cil-sync.git
./git_changes.sh /home/rstanonik/cil/CIL_Public_Data_JSON /home/rstanonik/cil```

**Comment by rstanonik** [comment]
[cil-sync-out.txt](https://github.com/ucsdlib/damsmanager/files/2896051/cil-sync-out.txt)

The sync stopped, no sign of a error in the log, which I'm attaching.  About 3.3T of data, a little over 10,000 json.  Any chance this is correct and the first download isn't 40T?

**Comment by hjsyoo** [comment]
@rstanonik The 10000 json sounds right (if there's one per object), but 3.3T sounds very low. Their site indicates 20T of publicly available data, and although some of this would be copyrighted (and therefore not for us to download), I didn't think the majority was. Let me ask in the email thread a little more pointedly.

**Comment by hjsyoo** [comment]
Documenting here that 3.3TB is very likely the full set of data we needed to pull, but it includes the data copyrighted by owners.

**Comment by lsitu** [comment]
Reopen it for QA.

**Comment by hjsyoo** [comment]
@rstanonik @lsitu We discovered at our dams-wg meeting today that the 3.22 TB in \rdcp-0126-cil\cil_harvest_2019-02-21\content_files must be an incomplete download. About 28K of the 31.6K files are only 1 KB, mostly .zip, .jpg, and .tif. The files that look correctly transferred are anywhere from 308GB to a few KB. Also, the files with complex names (e.g., 25726-Hoechst.zip) all seem to have transferred correctly, whereas all of the 1 KB files have only 'simple' filenames (e.g., 7750.jpg). What's the best next step here? I can ask Sean if 32K files is about right, but do we want to rerun @lsitu's script, or try a different mode of transfer?

**Comment by rstanonik** [comment]
Yes, ask Sean if the files are the correct size.
If Sean can compute checksums for all of the files or even just for the suspect files, then I can compute checksums to compare.
I'd prefer to run @lsitu's script again or a version of it, if we only need to download some files.

**Comment by lsitu** [comment]
@rstanonik I found a bug in the script for the mapping URL to download image files. I'll fix it so that you can run it again.

**Comment by rstanonik** [comment]
ok, thanks

**Comment by lsitu** [comment]
@mcritchlow / @rstanonik I've added PR https://github.com/ucsdlib/cil-sync/pull/3 to fix the download URL for image/non-video contents. It's ready for review now. Thanks.

**Comment by rstanonik** [comment]
Do I need to reply/approve the PR?

**Comment by lsitu** [comment]
@rstanonik I think @mcritchlow will. But it'll be nice if you can have an eye on it as well.

**Comment by lsitu** [comment]
Thanks @mcritchlow for keeping an eye on it and merging the PR.
@rstanonik I think you can update the repo and run the script again, which will correct the URL to download those non-video content files. I think those 1kb image small image files should be gone this time.

**Comment by rstanonik** [comment]
I updated cil-sync and re-ran and got this output

10023 files
From https://github.com/slash-segmentation/CIL_Public_Data_JSON
 * branch            master     -> FETCH_HEAD
Already up-to-date.
No new commits have been added

**Comment by rstanonik** [comment]
Should I also have updated CIL_Public_Data_JSON?

**Comment by rstanonik** [comment]
@hjsyoo Please confirm the 1k files are gone.

**Comment by hjsyoo** [comment]
@rstanonik I still see 1KB files in R:\rdcp-0126-cil\cil_harvest_2019-02-21\content_files. There's a new folder, R:\rdcp-0126-cil\cil_harvest_2019-03-06\content_files, but it looks empty.

**Comment by lsitu** [comment]
@rstanonik We may need to re-initiate the process, otherwise it just looks for new json added to the repository. Please remove all those JSON files from directory/rdcp-staging/rdcp-0126-cil so that the source file download process can be reinitiated. Thanks.

**Comment by rstanonik** [comment]
I removed the json and re-ran, which returned within seconds and produced this output
10023 files
From https://github.com/slash-segmentation/CIL_Public_Data_JSON
 * branch            master     -> FETCH_HEAD
Already up-to-date.
No new commits have been added

**Comment by lsitu** [comment]
@rstanonik This will happen when there are .json files existing in a folder called `metadata_source`. Could you rename folder `metadata_source`  in directory `cil_harvest_2019-02-21/pre/`?

**Comment by hjsyoo** [comment]
@rstanonik The checksum files are now in \rdcp-0126-cil\Admin\checksums_from_cil_sysadmin. Let me know if they're not what you need.

**Comment by rstanonik** [comment]
After removing the metadata_source directory, the git_changes.sh is running and outputting a list of json.

**Comment by rstanonik** [comment]
It looks like git_changes.sh is downloading everything again, but to a directory named cil_harvest_2019-03-07, even though most (all?) of the files are already in cil_harvest_2019-02-21

**Comment by lsitu** [comment]
@rstanonik Yes, it's correct for first time initiation. And the next time when you restart the process, the script will only download those new json files.

**Comment by rstanonik** [comment]
The download directory contains the date; for example cil_harvest_2019-03-07.

The next time it runs it will create a new directory; eg, cil_harvest_2019-03-09.

Will it find the old directory and only download files which aren't in the old directory?

**Comment by lsitu** [comment]
No. All the source files are downloaded in that same parent directory with the timestamp date. And it should always download all the content files for any new json files added to the repository.

**Comment by rstanonik** [comment]
[git_changes-out.txt](https://github.com/ucsdlib/damsmanager/files/2946641/git_changes-out.txt)

The run finished with an error.  I've attached the output.

Here is the space usage by the various runs.

du -sh --apparent-size cil_harvest_201*
100     cil_harvest_2018-12-14
3.3T    cil_harvest_2019-02-21
2.6T    cil_harvest_2019-03-07

**Comment by lsitu** [comment]
@rstanonik It looks like something may be wrong with the last item https://github.com/slash-segmentation/CIL_Public_Data_JSON/blob/master/Version8_6/DATA/CIL_PUBLIC_DATA/32103.json. Do you see content files 32103.tif, 32103.jpg, and 32103.zip are downloaded for source json 32103.json ?

**Comment by lsitu** [comment]
@hjsyoo / @arwenhutt I think the initial content files download wass interrupted by json https://github.com/slash-segmentation/CIL_Public_Data_JSON/blob/master/Version8_6/DATA/CIL_PUBLIC_DATA/46280.json, which is missing the `Data_type` section (/CIL_CCDB/Data_type).  The `Data_type` section that is required, which is used to determine the URL for downloading the contents. What should we do?

**Comment by lsitu** [comment]
@mcritchlow / @rstanonik I've added PR https://github.com/ucsdlib/cil-sync/pull/4 above to skip files downloaded with the option to choose the harvesting date. Also, it will continue content files download on error. 
The harvesting date option will ensure content files are writing to the existing folder with the date specify. For example, the following command will write to folder `cil_harvest_2019-03-07`:
```
./git_changes.sh $HOME/CIL_Public_Data_JSON /pub/data2/dams/dams-staging/rdcp-staging/rdcp-0126-cil 2019-03-07
```

The PR is ready for review now. Thanks.

**Comment by hjsyoo** [comment]
@lsitu I haven't heard back yet about how to handle JSON with missing main data files, but will let you know.
Can you review this brief documentation of what your script does, and let me know if any of my understanding is incorrect or incomplete?

1. The metadata are harvested. CIL stores its metadata in JSON at https://github.com/slash-segmentation/CIL_Public_Data_JSON. New JSON files in the CIL github that aren't in our previous download directory are copied to a new one: \rdcp-0126-cil\cil_harvest_YYYY-MM-DD\metadata_source. 
2. The data are harvested. CIL stores its image and video data files at https://cildata.crbs.ucsd.edu/media. Data files that are referenced in the new JSON files as CIL_CCDB.CIL.Image_files.File_path and  CIL_CCDB.CIL.Alternative_image_files.File_path are downloaded and copied to \rdcp-0126-cil\cil_harvest_YYYY-MM-DD\content_files.
3. The metadata are mapped from the new JSON files to our OLR template according to CIL Processing and Mapping Instructions.

**Comment by lsitu** [comment]
@hjsyoo Yes. The script does exactly as what you interpreted above.

**Comment by lsitu** [comment]
Thanks @mcritchlow for your quick reviewing and merging the PR.

@rstanonik I think we can restart the download script to continue download the json and content files to folder `cil_harvest_2019-03-07` by appending parameter `2019-03-07` to the end of the command now:
./git_changes.sh $HOME/CIL_Public_Data_JSON /pub/data2/dams/dams-staging/rdcp-staging/rdcp-0126-cil 2019-03-07

**Comment by rstanonik** [comment]
I did
cd cil-sync
git pull
./git_changes.sh /home/hjsyoo/CIL_Public_Data_JSON /mnt/isilon/rdcp-staging/rdcp-0126-cil 2019-03-07
It returned almost immediately.
The output was
6881 files
From https://github.com/slash-segmentation/CIL_Public_Data_JSON
 * branch            master     -> FETCH_HEAD
Already up-to-date.
No new commits have been added

**Comment by lsitu** [comment]
@mcritchlow / @rstanonik Sorry my mistake. Here is the PR https://github.com/ucsdlib/cil-sync/pull/5 with the condition to fix it. Thanks.

**Comment by lsitu** [comment]
@rstanonik It seems like @mcritchlow is not available now. Could you just merge PR https://github.com/ucsdlib/cil-sync/pull/5 so that you can restart the download? It's a very simple change. Thanks.

**Comment by rstanonik** [comment]
Thanks Longshou.

I just now did "git pull" and ran
 ./git_changes.sh /home/hjsyoo/CIL_Public_Data_JSON /mnt/isilon/rdcp-staging/rdcp-0126-cil 2019-03-07

It returned almost immediately.  It output the following
6881 files
From https://github.com/slash-segmentation/CIL_Public_Data_JSON
 * branch            master     -> FETCH_HEAD
Already up-to-date.
No new commits have been added

**Comment by lsitu** [comment]
@rstanonik The PR ucsdlib/cil-sync#5 haven't been merged yet and I just merged it. Try it now.

**Comment by rstanonik** [comment]
Thanks Longshou.
I did git pull and re-ran the script.
I is still running.
The output so far is
6881 files
From https://github.com/slash-segmentation/CIL_Public_Data_JSON
 * branch            master     -> FETCH_HEAD
Already up-to-date.
git diff --name-only --diff-filter=A 603698cca33dbcbd54f771715a239fb66b03e74e..603698cca33dbcbd54f771715a239fb66b03e74e

**Comment by rstanonik** [comment]
It finished and with no additional output messages, but the directory now has more files.
 du -sh --apparent-size cil_harvest_201*
3.3T    cil_harvest_2019-02-21
3.7T    cil_harvest_2019-03-07

I'll compare to the checksum list which Willy sent.

**Comment by gamontoya** [comment]
Has dependency: 

- [x] https://github.com/ucsdlib/damsmanager/issues/317

Do not close until the above is done.

**Comment by gamontoya** [comment]
@arwenhutt @lsitu Can we finally close this one? 😃
